/**
 * Markdown generated from the schema and templates (see scripts/gen-docs.ts).
 * Lives in src/ so a test can assert the committed docs are current.
 */

import { z } from 'zod';
import { Key, Track, Clip, Effect, EFFECT_PRESETS, Material, Part, Pattern, Scene, Sculpt, Settings, Shape, Anchor, Detail, CLIP_TYPES } from './core/schema.js';
import { TEMPLATES } from './templates/index.js';

type J = Record<string, unknown> & {
	type?: string | string[];
	properties?: Record<string, J>;
	required?: string[];
	description?: string;
	enum?: unknown[];
	const?: unknown;
	anyOf?: J[];
	oneOf?: J[];
	items?: J;
	prefixItems?: J[];
	minimum?: number;
	maximum?: number;
	exclusiveMinimum?: number;
	pattern?: string;
	maxItems?: number;
	minItems?: number;
	additionalProperties?: J | boolean;
};

const js = (s: z.ZodType) => z.toJSONSchema(s, { unrepresentable: 'any' }) as J;

function typeOf(s: J): string {
	if (s.const !== undefined) return `\`${JSON.stringify(s.const)}\``;
	if (s.enum) return s.enum.map((e) => `\`${String(e)}\``).join(' · ');
	const alts = s.anyOf ?? s.oneOf;
	if (alts && alts.every((a) => a.properties?.type?.const !== undefined)) return `one of ${alts.map((a) => `\`${String(a.properties!.type!.const)}\``).join(', ')}`;
	if (alts) return alts.map(typeOf).join(' or ');
	if (s.prefixItems) return `[${s.prefixItems.map(typeOf).join(', ')}]`;
	if (s.type === 'array' && s.items) return `${typeOf(s.items)}[]`;
	if (s.type === 'number' || s.type === 'integer') {
		const lo = s.exclusiveMinimum !== undefined ? `>${s.exclusiveMinimum}` : s.minimum !== undefined ? `≥${s.minimum}` : '';
		const hi = s.maximum !== undefined ? `≤${s.maximum}` : '';
		const range = [lo, hi].filter(Boolean).join(', ');
		return `${s.type === 'integer' ? 'integer' : 'number'}${range ? ` (${range})` : ''}`;
	}
	if (s.type === 'object' && s.properties?.to && s.properties?.side) return 'Anchor';
	if (s.type === 'object' && s.properties?.point) return '{ point: [x, y, z] }';
	if (s.type === 'object' && s.properties?.part && s.properties?.keys) return 'Track';
	if (s.type === 'object' && s.properties?.t) return 'Key';
	if (s.type === 'object' && s.properties) return 'object';
	if (s.type === 'array' && s.items?.properties && !s.items.properties.part && !s.items.properties.t) return 'object[]';
	if (s.type === 'object' && s.additionalProperties && typeof s.additionalProperties === 'object') return `{ key: ${typeOf(s.additionalProperties)} }`;
	if (s.type === 'string' && s.pattern) return 'string';
	return String(s.type ?? 'any');
}

function table(s: J): string {
	const props = s.properties ?? {};
	const req = new Set(s.required ?? []);
	const rows = Object.entries(props).map(([k, v]) => `| \`${k}\`${req.has(k) ? ' **required**' : ''} | ${typeOf(v).replace(/\|/g, '\\|')} | ${(v.description ?? '').replace(/\|/g, '\\|')} |`);
	return ['| field | type | meaning |', '|---|---|---|', ...rows].join('\n');
}

export function referenceMarkdown(): string {
	const shapes = (js(Shape).oneOf ?? js(Shape).anyOf ?? []) as J[];
	const out: string[] = [
		'# Scene reference',
		'',
		'> Generated from `src/core/schema.ts` by `scripts/gen-docs.ts`. Do not edit by hand.',
		'> Unknown fields are rejected, so a typo is an error rather than something silently ignored.',
		'',
		'Conventions: meters, +Y up, the model faces +Z, the model\'s left is +X, rotations are Euler degrees applied X → Y → Z.',
		'',
		'## Scene',
		'',
		table(js(Scene)),
		'',
		'## Settings',
		'',
		table(js(Settings)),
		'',
		'## Part',
		'',
		table(js(Part)),
		'',
		'### Shapes',
		''
	];
	for (const sh of shapes) {
		const name = (sh.properties?.type?.const as string) ?? '?';
		const fields = Object.entries(sh.properties ?? {}).filter(([k]) => k !== 'type');
		out.push(`**\`${name}\`** — ${fields.map(([k, v]) => `\`${k}\`${(sh.required ?? []).includes(k) ? '' : '?'}: ${typeOf(v)}${v.description ? ` (${v.description})` : ''}`).join('; ')}`, '');
	}
	out.push('### Anchor (`attach`, and sculpt/effect `at`)', '', table(js(Anchor)), '', 'A target can also be `{ "point": [x, y, z] }` in world space.', '');
	out.push('### Material', '', table(js(Material)), '', '### Pattern', '', table(js(Pattern)), '', '### Detail', '', table(js(Detail)), '');
	out.push('## Sculpt', '', table(js(Sculpt)), '');
	out.push('## Clip', '', table(js(Clip)), '', `Clip types: ${CLIP_TYPES.map((c) => `\`${c}\``).join(', ')}.`, '', '### Track', '', table(js(Track)), '', '### Key', '', table(js(Key)), '');
	out.push('## Effect', '', table(js(Effect)), '', `Presets: ${EFFECT_PRESETS.map((c) => `\`${c}\``).join(', ')}.`, '');
	return out.join('\n');
}

export function templatesMarkdown(): string {
	const out = ['# Templates', '', '> Generated by `scripts/gen-docs.ts`. Thumbnails are real renders.', '', 'Start from the closest one: `new_scene { "name": "…", "template": "<id>" }` or `clayform new <id>`.', ''];
	for (const t of TEMPLATES) {
		const s = t.scene;
		const roles = [...new Set(s.parts.map((p) => p.role).filter(Boolean))];
		out.push(
			`## ${t.title} — \`${t.id}\``,
			'',
			`<img src="templates/${t.id}.png" width="192" alt="${t.title} template, three-quarter view">`,
			'',
			t.description,
			'',
			`- tags: ${t.tags.join(', ')}`,
			`- parts: ${s.parts.map((p) => `\`${p.id}\``).join(', ')}`,
			roles.length ? `- roles: ${roles.join(', ')}` : '',
			s.palette ? `- palette: ${Object.entries(s.palette).map(([k, v]) => `\`${k}\` ${v}`).join(', ')}` : '',
			s.clips?.length ? `- clips: ${s.clips.map((c) => `\`${c.id}\` (${c.type})`).join(', ')}` : '',
			s.effects?.length ? `- effects: ${s.effects.map((e) => `\`${e.id}\` (${e.preset ?? 'custom'})`).join(', ')}` : '',
			s.sculpts?.length ? `- sculpts: ${s.sculpts.map((c) => `\`${c.id}\` (${c.kind})`).join(', ')}` : '',
			''
		);
	}
	return out.filter((l, i, a) => !(l === '' && a[i - 1] === '')).join('\n');
}

export function schemaJson(): string {
	const j = js(Scene) as Record<string, unknown>;
	j.$id = 'https://github.com/sezginkipel/clayform/blob/main/schema/clayform.schema.json';
	j.title = 'Clayform scene (clayform/1)';
	return JSON.stringify(j, null, 2) + '\n';
}
